### PR TITLE
Add headers for aisles and departments

### PR DESCRIPTION
**Pull request by toregeschliman**
Add Makefile with basic build commands `make sample` (default) or `make full` to load the data set without/with order_products__prior.csv
Add basic README

### CODE REVIEW

**Comment by freethejazz** [comment]
Hey Tore, thanks for putting this together! I've been slammed the last few evenings but will check it out this weekend.

**Comment by toregeschliman** [comment]
This gets data loaded, but something is definitely wonky (a pile of duplicates for orders and products, I suspect b/c/o OrderedItem. I'll keep working on it.

**Comment by freethejazz** [comment]
Hmm, looking at the code it doesn't seem like there should be any issues, but I also can't find explicit documentation on `neo4j-admin import`. If the API has changed, maybe some of the CLI flags are being silently ignored? I'll see if I can duplicate locally

**Comment by toregeschliman** [comment]
The headers for OrderedItem appear to be expecting a first ID column that isn't there. I'm going to experiment with replacing that path with a single relationship instead and calculate adjacency dynamically, but that won't match the presentation schema anymore.

**Comment by freethejazz** [comment]
Aaah, I can't believe I forgot about that. I needed a unique primary key on ordered items so they could be referenced later. +1 on moving to a single relationship, I've got a TODO to change that in the CSV import as well. It's going to be about the same amount of complexity to build the adjacency graph so we're not really losing anything.

**Comment by toregeschliman** [comment]
Alright, now that is working as expected.The adjacency query is going to be slightly slower now, something like 
```
MATCH (p:Product)-[r1:IN_ORDER]->()<-[r2:IN_ORDER]-(op)
WHERE r2.addToCartOrder = r1.addToCartOrder + 1
// or
WHERE r2.addToCartOrder > r1.addToCartOrder
RETURN p.name, op.name, COUNT(*) AS freq_after ORDER BY freq_after DESC LIMIT 5
```
which I think will work out to 1 extra db hit per order or so, performance-wise, so not fatal. And you can drop the filter altogether to calculate commonality instead of sequence, and for a nice short one-step relationship like that, you could do: 
```
PROFILE
MATCH (p:Product) WHERE p.name CONTAINS "Red Wine"
WITH DISTINCT p, p.name AS name LIMIT 1
MATCH (p)-[:IN_ORDER]->()<-[:IN_ORDER]-(op)
WITH name, op, count(*) AS pf // pf, or "path frequency", the count of shared orders
WHERE pf > 1 // This is useful on the smaller test data set to throw away statistical noise
WITH name, op, SIZE( (op)-[:IN_ORDER]->() ) AS sgf, pf // sgf, or "subgraph frequency", the total orders the other product is in
RETURN name, op.name, toFloat(pf)/toFloat(sgf) AS rel ORDER BY rel DESC LIMIT 10 // pf-isgf, does not roll off the tongue
```

**Comment by freethejazz** [comment]
Awesome, thanks! I'll probably rework the query that generates the adjacency graph to account for the modified graph structure, if possible, so that it's easier to write more complex queries involving adjacency.

**Pull request merged**
